### ISSUE TITLE
B18 - Implement friend request and notification

### ISSUE THREAD

**Issue by banctilrobitaille** [gti525/e17-reseau-social#10]
We should implement friend request on non-friend user page and friend request notification on personnal page.

**Comment by alexandremalo** [comment]
![image](https://cloud.githubusercontent.com/assets/9504524/26375771/328d7bf0-3fd8-11e7-8f96-6c5fb19eba24.png)

**Comment by alexandremalo** [comment]
I will add the list of pending friend request on top of the friend list

**Comment by alexandremalo** [comment]
![image](https://cloud.githubusercontent.com/assets/9504524/26375895/8d96b7c8-3fd8-11e7-968e-1144b6c7e173.png)

**Comment by alexandremalo** [comment]
#27 Pending to merge in staging for testing
