### ISSUE TITLE
B3 - Add the missing field in registration modal

### ISSUE THREAD

**Issue by banctilrobitaille** [gti525/e17-reseau-social#2]
A first draft of the registration modal as been implemented, but according to the spec doc it must contain the following fields (adresse courriel, son nom, son prénom, son adresse, sa ville, son code postal et sa province), @MarcAntoineHebert  already sent me the code, but I still have to add the missing field in the modal and adjust the validation.

**Comment by MarcAntoineHebert** [comment]
New fields added.
<img width="448" alt="capture d ecran 2017-05-23 a 18 44 38" src="https://cloud.githubusercontent.com/assets/12803037/26379585/ee206d6e-3fe7-11e7-9902-94fbd75450d3.png">

**Comment by MarcAntoineHebert** [comment]
PR #29 ready for a review.

**Comment by alexandremalo** [comment]
modal to big? @banctilrobitaille

**Comment by banctilrobitaille** [comment]
Je vais faire 2 sections je pense, apres les infos général on va faire next et ça va être l'autre section @alexandremalo
