### ISSUE TITLE
B8 - Add missing field in ticket component

### ISSUE THREAD

**Issue by banctilrobitaille** [gti525/e17-reseau-social#6]
According to the spec doc these attributes should be available : nom du spectacle, l'artiste, la date, l'emplacement, le montant ainsi que le nom et le prénom de l'acheteur. The most relevant information could be in the ticket component and the others in the details modal.

**Comment by alexandremalo** [comment]
![image](https://cloud.githubusercontent.com/assets/9504524/26375701/f5c139c8-3fd7-11e7-8f88-f0bd4b2296c7.png)

**Comment by MarcAntoineHebert** [comment]
I will add : artiste, montant, nom et prénom de l'acheteur.

**Comment by MarcAntoineHebert** [comment]
Done
<img width="273" alt="capture d ecran 2017-05-23 a 17 03 34" src="https://cloud.githubusercontent.com/assets/12803037/26376259/df0f0b22-3fd9-11e7-823a-e0d89441d9d3.png">

And I respected the monetary format #16

**Comment by MarcAntoineHebert** [comment]
Please review my PR #26
