### ISSUE TITLE
B14 - Implement ticket transfert page/modal

### ISSUE THREAD

**Issue by banctilrobitaille** [gti525/e17-reseau-social#8]
A ticket transfert page should be implemented on which we can select one of our friend to transfer the ticket to. It could be on the ticket details page/modal.

**Comment by alexandremalo** [comment]
![image](https://cloud.githubusercontent.com/assets/9504524/26377243/7d0e2e54-3fdd-11e7-92a2-e67a9a2cc446.png)

**Comment by alexandremalo** [comment]
modal toggle off need to be sent after success

**Comment by alexandremalo** [comment]
@banctilrobitaille yoyoy
